In [96]:
import pandas as pd
import re

In [97]:
def clean_str(s):
    try:
        return re.sub(r"[^a-zA-Z0-9 ]+","",s).strip()
    except:
        return s

In [102]:
grant_schedule = pd.read_csv("https://docs.google.com/spreadsheets/d/1AEALzh1Gwx_WzQnJk4bq_rrsv_SwFgqZxlpl_imgqkk/pub?gid=0&single=true&output=csv")
grant_schedule["Town Grant Name"] = grant_schedule["Town Grant Name"].apply(clean_str)
grant_schedule.to_csv("../data/calendar.csv",index=False)
grant_schedule.head()

,Appropriation Name,Town Grant Name,FY 17 Net Appropriation,Jul,Aug,Sept,Oct,Nov,Dec,Jan,Feb,Mar,Apr,May,Jun,Unspecified,Within Available Approps or Capping Language,MOE Issues,Statutory Reference
0,Reimbursement to Towns for Loss of Taxes on St...,PILOT StateOwned Real Property,"$66,730,441",NaN,NaN,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No,"12-19a, 12-19b, 12-19c, 4b-39"
1,Reimbursements to Towns for Loss of Taxes on P...,PILOT Colleges Hospitals,"$114,950,770",NaN,NaN,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No,"12-19b, 12-20a, 12-18b,"
2,Reimbursement Property Tax - Disability Exemption,NaN,"$374,065",NaN,NaN,NaN,NaN,NaN,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No,12-94a and 12-81(55)
3,Distressed Municipalities,NaN,"$5,423,986",NaN,NaN,NaN,NaN,NaN,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No,"12-81(59), (60), (70)12-81k, 32-9p through 32-..."
4,Property Tax Relief Elderly Circuit Breaker,NaN,"$19,176,502",NaN,NaN,NaN,NaN,NaN,100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No,"12-170aa, 12-170bb, 12-170cc"

In [103]:
town_runs = pd.read_csv("https://docs.google.com/spreadsheets/d/1AEALzh1Gwx_WzQnJk4bq_rrsv_SwFgqZxlpl_imgqkk/pub?gid=825246286&single=true&output=csv",
                        header=[0,1])

keepers = filter(lambda x: "Unnamed:" not in x[0], town_runs.columns)

town_runs = town_runs[keepers]
town_runs.columns = map(lambda x: clean_str(x[0]) + "_" + clean_str(x[1]), keepers)
town_runs = town_runs.set_index("Town_Town")
town_runs.head()

,PILOT StateOwned Real Property_FY 2017,PILOT StateOwned Real Property_FY 2018,PILOT Colleges Hospitals_FY 2017,PILOT Colleges Hospitals_FY 2018,Mashantucket Pequot And Mohegan Fund Grant_FY 2017,Mashantucket Pequot And Mohegan Fund Grant_FY 2018,Adult Education_FY 2017,Adult Education_FY 2018,Education Cost Sharing_FY 2017,Education Cost Sharing_FY 2018,MRSA Municipal Revenue Sharing Grant_FY 2017,MRSA Municipal Revenue Sharing Grant_FY 2018,MRSA Additional Payment in Lieu of Taxes_FY 2017,MRSA Additional Payment in Lieu of Taxes_FY 2018,MRSA Motor Vehicle Property Tax Grants_FY 2017,MRSA Motor Vehicle Property Tax Grants_FY 2018,TOTAL Statutory Formula Aid_FY 2017,TOTAL Statutory Formula Aid_FY 2018
Town_Town,,,,,,,,,,,,,,,,,,
Andover,"4,211",0,0,0,"14,975",0,0,0,"2,331,185","820,402","66,705","96,020",0,0,0,0,"2,417,076","916,422"
Ansonia,"44,259",0,0,0,"160,809",0,"107,666","106,337","16,473,543","16,476,897","605,442","643,519","19,652","20,543",0,"686,815","17,411,371","17,934,111"
Ashford,44,0,0,0,"23,966",0,0,0,"3,859,564","1,873,710","87,248","125,591",0,0,0,"5,239","3,970,822","2,004,540"
Avon,0,0,0,0,"19,195",0,"1,985","1,789","731,456",0,"374,711","539,387",0,0,0,0,"1,127,347","541,176"
Barkhamsted,"1,682",0,0,0,"16,970",0,"1,595","1,629","1,633,686","637,170","76,324","109,867",0,0,0,0,"1,730,257","748,666"

In [104]:
town_runs.to_json("../data/town_runs.json",orient="index")