In [70]:
import pandas as pd
import re

In [71]:
def clean_str(s):
    try:
        return re.sub(r"[^a-zA-Z0-9 ]+","",s).strip()
    except:
        return s

In [72]:
grant_schedule = pd.read_csv("https://docs.google.com/spreadsheets/d/1AEALzh1Gwx_WzQnJk4bq_rrsv_SwFgqZxlpl_imgqkk/pub?gid=0&single=true&output=csv")
grant_schedule["Town Grant Name"] = grant_schedule["Town Grant Name"].apply(clean_str)
grant_schedule.to_csv("../data/calendar.csv",index=False)
grant_schedule.tail()

,Appropriation Name,Town Grant Name,FY 17 Net Appropriation,Jul,Aug,Sept,Oct,Nov,Dec,Jan,Feb,Mar,Apr,May,Jun,Unspecified,Within Available Approps or Capping Language,MOE Issues,Statutory Reference
26,School Readiness Quality Enhancement,NaN,"$3,797,742",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,Yes,No,10-16o through 10-16r
27,Connecticard Payments,NaN,"$781,820",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100%,NaN,NaN,NaN,Yes,No,11-31b
28,Venereal Disease Control - offset by Insurance...,NaN,"$197,171",25%,NaN,NaN,25%,NaN,NaN,25%,NaN,NaN,25%,NaN,NaN,X,Yes,No,None
29,Mashantucket Pequot Grant,Mashantucket Pequot And Mohegan Fund Grant,"$58,076,612",NaN,NaN,NaN,NaN,NaN,NaN,33.30%,NaN,NaN,33.30%,NaN,33.30%,NaN,Yes,No,3-55j
30,State Charter School,NaN,"$103,877,000",25%,NaN,25%,NaN,NaN,NaN,25%,NaN,NaN,25%,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
# Updated with Aug. 18 updates
#town_runs = pd.read_csv("https://docs.google.com/spreadsheets/d/1AEALzh1Gwx_WzQnJk4bq_rrsv_SwFgqZxlpl_imgqkk/pub?gid=825246286&single=true&output=csv",
#                        header=[0,1])

town_runs = pd.read_csv("https://docs.google.com/spreadsheets/d/1kEJqPFCxrVDjBJlN6MW5L3c53tY6KEf19D4Q7ZpYpZk/pub?gid=966644806&single=true&output=csv",
                       header=[0,1])

keepers = filter(lambda x: "Unnamed:" not in x[0], town_runs.columns)

town_runs = town_runs[keepers]
town_runs.columns = map(lambda x: clean_str(x[0]) + "_" + clean_str(x[1]), keepers)
town_runs = town_runs.set_index("Town_Town")
town_runs.head()

,PILOT StateOwned Real Property_FY 2017,PILOT StateOwned Real Property_FY 2018,PILOT Colleges Hospitals_FY 2017,PILOT Colleges Hospitals_FY 2018,Mashantucket Pequot And Mohegan Fund Grant_FY 2017,Mashantucket Pequot And Mohegan Fund Grant_FY 2018,Adult Education_FY 2017,Adult Education_FY 2018,Education Cost Sharing_FY 2017,Education Cost Sharing_FY 2018,MRSA Municipal Revenue Sharing Grant_FY 2017,MRSA Municipal Revenue Sharing Grant_FY 2018,MRSA Additional Payment in Lieu of Taxes_FY 2017,MRSA Additional Payment in Lieu of Taxes_FY 2018,MRSA Motor Vehicle Property Tax Grants_FY 2017,MRSA Motor Vehicle Property Tax Grants_FY 2018,TOTAL Statutory Formula Aid_FY 2017,TOTAL Statutory Formula Aid_FY 2018,Priority School District_FY 2017,Priority School District_FY 2018
Town_Town,,,,,,,,,,,,,,,,,,,,
Andover,"4,211",0,0,0,"14,975",0,0,0,"2,331,185","466,237","66,705",0,0,0,0,0,"2,417,076","466,237",NaN,0
Ansonia,"44,259",0,0,0,"160,809",0,"107,666","106,337","16,473,543","16,473,543","605,442",0,"19,652",0,0,"167,288","17,411,371","16,747,168",NaN,0
Ashford,44,0,0,0,"23,966",0,0,0,"3,859,564","1,157,869","87,248",0,0,0,0,0,"3,970,822","1,157,869",NaN,0
Avon,0,0,0,0,"19,195",0,"1,985","1,789","731,456",0,"374,711",0,0,0,0,0,"1,127,347","1,789",NaN,0
Barkhamsted,"1,682",0,0,0,"16,970",0,"1,595","1,629","1,633,686",0,"76,324",0,0,0,0,0,"1,730,257","1,629",NaN,0

In [74]:
town_runs.to_json("../data/town_runs.json",orient="index")

In [75]:
town_runs.to_csv("../data/town_runs.csv")